[build]
  base = "my-react-app"
  publish = "dist"
  command = "npm install --no-audit --no-fund && npm run build"

[build.environment]
  NODE_VERSION = "20"
  # На случай проблем с optional native зависимостями (rollup)
  # NPM_CONFIG_OPTIONAL = "false"

# Маршрутизация для SPA (на случай, если Netlify не подхватит _redirects из public)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
